# rke-deployment/group_vars/all.yml
---
# Ansible connection settings
ansible_user: root # User for SSH login on target nodes
ansible_become: yes    # Use sudo for elevated privileges

# RHEL OS specific
rhel_version: 8 # or 9
firewalld_zone: public

# Container Runtime
container_runtime: "docker" # Options: "containerd" or "docker"

# Kubernetes & RKE versions
# RKE 2.5.7 supports specific K8s versions, check Rancher docs for compatibility.
kubernetes_version: "v1.20.15-rancher1-1" # Example K8s version compatible with RKE 2.5.7
rke_binary_version: "v1.2.11" # RKE CLI binary version for RKE 2.5.7 deployments

# RKE Cluster Configuration
cluster_name: "rke-ktbcs"
cluster_dns_provider: "coredns"
cluster_network_plugin: "calico" # Options: "flannel", "calico"
cluster_service_cidr: "10.43.0.0/16"
cluster_cluster_cidr: "10.42.0.0/16"
cluster_api_server_url: "{{ groups['load_balancer'][0] if 'load_balancer' in groups else hostvars[groups['rke_masters'][0]]['ansible_host'] }}:6443" # Use LB IP or first master IP

# RKE Cluster config overrides (optional)
# rke_extra_args:
#   kube-api:
#     - "service-node-port-range=30000-32767"

# Rancher specific (optional, for later Rancher deployment on RKE)
# rancher_server_hostname: "rancher.yourdomain.com"
# rancher_version: "v2.5.7" # The Rancher Server version to install on the cluster