# rke-deployment/roles/load_balancer/tasks/main.yml
---
- name: Install HAProxy
  ansible.builtin.yum:
    name: haproxy
    state: present

- name: Configure HAProxy for Kubernetes API
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: haproxy
    mode: '0640'
  notify: Restart haproxy

- name: Start and enable HAProxy service
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Open HAProxy ports in firewalld
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    zone: "{{ firewalld_zone }}"
    state: enabled
    permanent: yes
  loop:
    - 6443 # K8s API
    - 80 # HTTP for Ingress
    - 443 # HTTPS for Ingress
    - 9000 # HAProxy Stats (optional)
  notify: Reload firewalld