# rke-deployment/roles/k8s_prereqs/tasks/main.yml
---
- name: Disable SWAP
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
  changed_when: true

- name: Remove swap entry from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^\s*[^#]+\s+swap\s+swap\s+.*$'
    state: absent

- name: Load overlay and br_netfilter kernel modules
  ansible.builtin.community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Add modules to /etc/modules-load.d/k8s.conf
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl parameters for Kubernetes
  ansible.builtin.template:
    src: k8s.conf.j2
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl

- name: Set SELinux to permissive mode
  ansible.posix.selinux:
    state: permissive

- name: Update SELinux config to permissive
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
    state: present

- name: Install Kubernetes prerequisites packages
  ansible.builtin.yum:
    name:
      - socat
      - conntrack-tools
      - crictl # For containerd interaction
      - iptables
    state: present

- name: Start and enable firewalld
  ansansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Add K8s custom firewalld service (master ports)
  ansible.builtin.template:
    src: firewalld_k8s.xml.j2
    dest: /etc/firewalld/services/kubernetes.xml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['rke_masters']

- name: Add K8s custom firewalld service (worker ports, if not master)
  ansible.builtin.template:
    src: firewalld_k8s_worker.xml.j2 # A different template for worker specific ports
    dest: /etc/firewalld/services/kubernetes-worker.xml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['rke_workers'] and inventory_hostname not in groups['rke_masters'] # For dedicated workers

- name: Open common ports (SSH, Ingress)
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    zone: "{{ firewalld_zone }}"
    state: enabled
    permanent: yes
  loop:
    - 22
    - 80
    - 443
  notify: Reload firewalld

- name: Open RKE/K8s specific ports for Master nodes
  ansible.posix.firewalld:
    service: kubernetes # Using custom service
    zone: "{{ firewalld_zone }}"
    state: enabled
    permanent: yes
  when: inventory_hostname in groups['rke_masters']
  notify: Reload firewalld

- name: Open RKE/K8s specific ports for Worker nodes
  ansible.posix.firewalld:
    service: kubernetes-worker # Using custom service
    zone: "{{ firewalld_zone }}"
    state: enabled
    permanent: yes
  when: inventory_hostname in groups['rke_workers'] and inventory_hostname not in groups['rke_masters']
  notify: Reload firewalld

- name: Open Flannel/Calico (CNI) specific ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: "{{ firewalld_zone }}"
    state: enabled
    permanent: yes
  loop:
    - "8472/udp" # Flannel VXLAN
    # - "6783/tcp" # Calico
    # - "6783/udp" # Calico
    # - "6784/udp" # Calico
  when: cluster_network_plugin == "flannel"
  notify: Reload firewalld