# rke-deployment/roles/container_runtime/tasks/main.yml
---
- name: Add Docker GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: Add Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/{{ rhel_version }}/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install containerd.io (for both Docker and Containerd setups)
  ansible.builtin.yum:
    name: containerd.io
    state: present

- name: Configure containerd for systemd cgroup driver
  when: container_runtime == "containerd"
  block:
    - name: Ensure containerd config directory exists
      ansible.builtin.file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config
      ansible.builtin.command: containerd config default
      register: containerd_default_config
      changed_when: containerd_default_config.rc != 0

    - name: Save default containerd config to temporary file
      ansible.builtin.copy:
        content: "{{ containerd_default_config.stdout }}"
        dest: /tmp/containerd_config.toml

    - name: Set SystemdCgroup = true in containerd config
      ansible.builtin.replace:
        path: /tmp/containerd_config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
        after: '^\[plugins\."io\.containerd\.grpc\.v1\.cri"\]$'

    - name: Move configured containerd config to /etc/containerd/config.toml
      ansible.builtin.copy:
        src: /tmp/containerd_config.toml
        dest: /etc/containerd/config.toml
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
      notify: Restart containerd

    - name: Enable and start containerd service
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: yes

- name: Install Docker Engine
  when: container_runtime == "docker"
  block:
    - name: Install docker-ce, docker-ce-cli
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
        state: present

    - name: Ensure docker config directory exists
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure Docker daemon for systemd cgroup driver
      ansible.builtin.copy:
        content: |
          {
            "exec-opts": ["native.cgroupdriver=systemd"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "100m"
            },
            "storage-driver": "overlay2"
          }
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
      notify: Restart docker

    - name: Enable and start docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes