# rke-deployment/roles/common/tasks/main.yml
---
- name: Ensure EPEL repository is installed
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'RedHat' and rhel_version == 8

- name: Install common packages
  ansible.builtin.yum:
    name:
      - curl
      - wget
      - git
      - vim
      - net-tools
      - jq
      - chrony
    state: present

- name: Start and enable chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: yes

- name: Create '{{ ansible_user }}' user
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
    create_home: yes
    shell: /bin/bash
    groups: wheel # Add to wheel group for sudo access

- name: Set up authorized_keys for '{{ ansible_user }}' user
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" # Path to your Ansible control host's public key

- name: Grant NOPASSWD sudo privileges to '{{ ansible_user }}'
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    create: yes
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s

- name: Disable root login via SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify: Restart sshd

- name: Disable password authentication via SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart sshd

- name: Update all packages
  ansible.builtin.yum:
    name: "*"
    state: latest