# rke-deployment/roles/container_runtime/handlers/main.yml
---
- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted