# rke-deployment/roles/k8s_prereqs/handlers/main.yml
---
- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: true

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true